#eureka配置
#server:
#  port: 1111
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#     defaultZone: http://localhost:1111/eureka/

#服务配置
#spring:
#  application:
#    name: compute-service
#server:
#  port: 2222
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:1111/eureka/

#ribbon配置
#server:
#  port: 3333
#spring:
#  application:
#    name: ribbon-service
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:1111/eureka/

#profile配置
spring:
  profiles:
    active: dev
