#eureka配置
spring:
  application:
    name: eureka-server
server:
  port: 1112
#  ssl:
#    key-store: .keystore
#    key-store-password: 1111aaaa
#    key-store-type: JKS
#    key-alias: tomcat-
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:1111/eureka/
#服务配置
#spring:
#  application:
#    name: compute-service
#server:
#  port: 2222
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:1111/eureka/

#ribbon配置
#server:
#  port: 3333
#spring:
#  application:
#    name: ribbon-service
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:1111/eureka/